<a href="https://colab.research.google.com/github/Tanveer132/ML-Practices-End-to-End/blob/main/Numpy_Mathematical_computing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy :**

    Mathematical computing library.
    Supportive to large number of data like multidimensional array.
    operations like FT, mean, max, min, create random number list can be done.
     


In [1]:
import numpy as np

**Create array and describe array**

In [2]:
#create 1D array
array_1d=np.array([1,2,3,4,5])
print(array_1d.dtype)
print(array_1d.shape)
print(array_1d.size)
print(array_1d.ndim)

array=np.array([1,'s'])
print(array.dtype)
print(array.shape)
print(array.size)
print(array.ndim)

int64
(5,)
5
1
<U21
(2,)
2
1


In [3]:
#Create 2D array

array_2D=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(array.dtype)
print(array.shape)
print(array.size)
print(array.ndim)

<U21
(2,)
2
1


In [4]:
#Array of ones and zeros

array_1=np.ones((2,5),dtype=int)
print(array_1)
array_0=np.zeros((2,5),dtype=int)
print(array_0)

[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [5]:
array_bool=np.ones((2,5),dtype=bool)
print(array_bool)

[[ True  True  True  True  True]
 [ True  True  True  True  True]]


In [18]:
#create array using random elements in range
random_array=np.random.randint(-2,5,size=(2,3))
print(random_array)

#select random choice in given array
choice=np.random.choice(random_array.flatten(),size=(1,3))
print(choice)
#bool should be 0 and 1 only
random_bool=np.random.randint(0,2,size=(2,3),dtype=bool)  
print(random_bool)

[[ 1  0 -1]
 [ 0 -2  4]]
[[1 4 0]]
[[ True False  True]
 [False False False]]


In [7]:
#array with given number of elements in given range
lin_array=np.linspace(0,10,50)
print(lin_array)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [8]:
#array in given range with given step
range_array=np.arange(0,10,2)
print(range_array)

range_array=np.arange(0,10).reshape((2,5))
print(range_array)

[0 2 4 6 8]
[[0 1 2 3 4]
 [5 6 7 8 9]]


**Operations on array using numpy**

In [9]:
#reshape array
#new size(row*column) = old size(row*column)
reshaped_array=np.reshape(lin_array,(5,10))
print(reshaped_array)

[[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
   1.2244898   1.42857143  1.63265306  1.83673469]
 [ 2.04081633  2.24489796  2.44897959  2.65306122  2.85714286  3.06122449
   3.26530612  3.46938776  3.67346939  3.87755102]
 [ 4.08163265  4.28571429  4.48979592  4.69387755  4.89795918  5.10204082
   5.30612245  5.51020408  5.71428571  5.91836735]
 [ 6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
   7.34693878  7.55102041  7.75510204  7.95918367]
 [ 8.16326531  8.36734694  8.57142857  8.7755102   8.97959184  9.18367347
   9.3877551   9.59183673  9.79591837 10.        ]]


In [10]:
#convert multidimensional array into 1D array
# flatten()--> doesn't make change in original array
flatten_array=reshaped_array.flatten()
print(flatten_array)
flatten_array[0]=1000
print(reshaped_array)

# ravel()--> make change in original array
ravel_array=reshaped_array.ravel()
print(ravel_array)
ravel_array[0]=1000.0
print(reshaped_array)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
   1.2244898   1.42857143  1.63265306  1.83673469]
 [ 2.04081633  2.24489796  2.44897959  2.65306122  2.85714286  3.06122449
   3.26530612  3.46938776  3.67346939  3.87755102]
 [ 4.08163265  4.28571429  4.48979592  4.69387755  4.89795918  5.10204082
   5.30612245  5.51020408  5.71428571  5.91836735]
 [ 6.12244898  

In [11]:
#transpose array

transpose_array=reshaped_array.transpose()
print(transpose_array)

[[1.00000000e+03 2.04081633e+00 4.08163265e+00 6.12244898e+00
  8.16326531e+00]
 [2.04081633e-01 2.24489796e+00 4.28571429e+00 6.32653061e+00
  8.36734694e+00]
 [4.08163265e-01 2.44897959e+00 4.48979592e+00 6.53061224e+00
  8.57142857e+00]
 [6.12244898e-01 2.65306122e+00 4.69387755e+00 6.73469388e+00
  8.77551020e+00]
 [8.16326531e-01 2.85714286e+00 4.89795918e+00 6.93877551e+00
  8.97959184e+00]
 [1.02040816e+00 3.06122449e+00 5.10204082e+00 7.14285714e+00
  9.18367347e+00]
 [1.22448980e+00 3.26530612e+00 5.30612245e+00 7.34693878e+00
  9.38775510e+00]
 [1.42857143e+00 3.46938776e+00 5.51020408e+00 7.55102041e+00
  9.59183673e+00]
 [1.63265306e+00 3.67346939e+00 5.71428571e+00 7.75510204e+00
  9.79591837e+00]
 [1.83673469e+00 3.87755102e+00 5.91836735e+00 7.95918367e+00
  1.00000000e+01]]


**Mathematical operations on array**

In [12]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,6,7,8,9])

In [13]:
#addition
add_arr=np.add(arr1,arr2)
print(arr1)
print(arr2)
print(add_arr)


[1 2 3 4 5]
[5 6 7 8 9]
[ 6  8 10 12 14]


In [14]:
#subtraction
sub_arr=np.subtract(arr2,arr1)
print(arr1)
print(arr2)
print(sub_arr)


[1 2 3 4 5]
[5 6 7 8 9]
[4 4 4 4 4]


In [15]:
#multiplication
mul_arr=np.multiply(arr1,arr2)
print(arr1)
print(arr2)
print(mul_arr)

#matrix multiplication
dot_arr=arr1.dot(arr2)
print(arr1)
print(arr2)
print(dot_arr)

[1 2 3 4 5]
[5 6 7 8 9]
[ 5 12 21 32 45]
[1 2 3 4 5]
[5 6 7 8 9]
115


In [16]:
#max-->gives max element and argmax-->gives index of max element

print(arr1.argmax())
print(arr1.max())

print(arr1.argmax(axis=0))
print(arr1.max(axis=0))


4
5
4
5


**Statastical operations on array**

In [21]:
#min value
print(np.amin(arr1))
#max value
print(np.amax(arr1))
#standard deviation
print(np.std(arr1))
#mean
print(np.mean(arr1))
#median
print(np.median(arr1))
#range
print(np.ptp(arr1))
#average 
print(np.average(arr1))


1
5
1.4142135623730951
3.0
3.0
4
3.0
