<a href="https://colab.research.google.com/github/Tanveer132/ML-Practices-End-to-End/blob/main/TimeSeriesAnalysis_Forecasting_Multivariate_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Time Series Analysis - Forecasting with LSTM

preparing multivariate data

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
col_1=np.array([10,20,30,40,50,60,70,80,90])
col_2=np.array([15,25,35,45,55,65,75,85,95])

In [ ]:
out=[]
for i in range(len(col_1)):
  out.append(col_1[i]+col_2[i])
out_col=np.array(out)

In [ ]:
out_col

array([ 25,  45,  65,  85, 105, 125, 145, 165, 185])

In [ ]:
out_col=col_1+col_2
out_col

array([ 25,  45,  65,  85, 105, 125, 145, 165, 185])

In [ ]:
col_1=col_1.reshape(len(col_1),1)
col_2=col_2.reshape(len(col_1),1)
out_col=out_col.reshape(len(col_1),1)

In [ ]:
data=np.hstack((col_1,col_2,out_col))

In [ ]:
data

array([[ 10,  15,  25],
       [ 20,  25,  45],
       [ 30,  35,  65],
       [ 40,  45,  85],
       [ 50,  55, 105],
       [ 60,  65, 125],
       [ 70,  75, 145],
       [ 80,  85, 165],
       [ 90,  95, 185]])

In [ ]:
def feature_transform(n_steps,data):
  x=[]
  y=[]
  for i in range(n_steps,len(data)+1):
    x.append(data[i-n_steps:i,:-1])
    y.append(data[i-1,-1])
  return np.array(x),np.array(y)

In [ ]:
n_steps=3
x,y=feature_transform(n_steps,data)

In [ ]:
x,y

In [ ]:
x.shape

(7, 3, 2)

In [ ]:
from keras.layers import Dense,LSTM
from keras.models import Sequential
model=Sequential()
model.add(LSTM(50,activation='relu',input_shape=(n_steps,x.shape[2])))
model.add(Dense(1))
model.compile(optimizer='adam',loss="mse")

In [ ]:
history=model.fit(x,y,epochs=100)

In [ ]:
#testing
xtest=np.array([[80,85],[90,95],[100,105]])
xtest=xtest.reshape((1,3,2))

In [ ]:
ypred= model.predict(xtest)
ypred

array([[207.27235]], dtype=float32)